services:
  mysql:
    image: mysql:8.4
    container_name: s-care-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scare
      MYSQL_USER: scare
      MYSQL_PASSWORD: scare
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: s-care-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: scare
      DB_USER: scare
      DB_PASSWORD: scare
      JWT_SECRET: s-care-mini-jwt-secret
      JWT_REFRESH_SECRET: s-care-mini-refresh-secret
      REDIS_URL: redis://redis:6379
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      mysql:
        condition: service_healthy

  client:
    build: ./client
    container_name: s-care-client
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - app
  redis:
    image: redis:7-alpine
    container_name: s-care-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
volumes:
  mysql_data:
  uploads_data:
